---
apiVersion: v1
kind: Namespace
metadata:
  name: test3
---
apiVersion: v1
kind: Pod
metadata:
  name:      notag
  namespace: test3
  labels:
    test: label
spec:
  containers:
    - name:  pause
      image: gcr.io/google_containers/pause-amd64
