---
apiVersion: v1
kind: Namespace
metadata:
  name: test4
  labels:
    name: test4
---
apiVersion: v1
kind: Pod
metadata:
  name:      sourcefail
  namespace: test4
  labels:
    test: label
spec:
  containers:
    - name:  pause
      image: registry.hub.docker.com/library/nginx
