language: go
go: 1.10.x
services:
- docker
install: true
notifications:
  email: false
before_install:
  - curl https://glide.sh/get | sh
  - go get github.com/mattn/goveralls
script: 
  - make goveralls
after_success:
  provider: script
  script: make build && make push 
  if: tag IS present
