language: go
go: 1.10.x
sudo: true
services:
- docker
install: true
notifications:
  email: false
before_install:
  - curl https://glide.sh/get | sh
  - go get github.com/mattn/goveralls
  - wget https://cdn.rawgit.com/kubernetes-sigs/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.10.sh && \
    chmod +x ./dind-cluster-v1.10.sh
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && \
script: 
  - make goveralls
  - ./dind-cluster-v1.10.sh up 
  - sudo mv $HOME/.kubeadm-dind-cluster/kubectl /usr/local/bin/
  - make buildhash && make pushhash
  - make deploydindk8s
  - make e2etests
after_success:
  - test -n "$TRAVIS_TAG" && make build && make push 
