language: go
go: 1.10.x
services:
- docker
install: true
notifications:
  email: false
before_install:
  - curl https://glide.sh/get | sh
script: 
  - glide install
  - go test ./...
after_success:
  - make build
  - make push 
