language: go
go: 1.10.x
sudo: true
services:
- docker
install: true
notifications:
  email: false
env:
  - TEST_SUITE=goveralls
  - TEST_SUITE=buildpushhash
  - TEST_SUITE=travise2e
before_install:
  - go get github.com/mattn/goveralls
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
  - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
  - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"
  - echo "${DOCKERPASSWORD}" | docker login -u "${DOCKERUSERNAME}" --password-stdin
script: 
  - "make $TEST_SUITE"
after_success:
  - test -n "$TRAVIS_TAG" && make build && make push 
