language: go
go: 1.10.x
sudo: true
services:
- docker
install: true
notifications:
  email: false
before_install:
  - curl https://glide.sh/get | sh
  - go get github.com/mattn/goveralls
  - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
  - mkdir -p .bin; mv ./kubectl .bin/kubectl && chmod +x .bin/kubectl
  - export PATH="$TRAVIS_BUILD_DIR/.bin:$PATH"
  - wget https://cdn.rawgit.com/kubernetes-sigs/kubeadm-dind-cluster/master/fixed/dind-cluster-v1.10.sh
  - chmod +x dind-cluster-v1.10.sh
  - export PATH="$HOME/.kubeadm-dind-cluster:$PATH"
script: 
  - make goveralls
  - make travise2e
after_success:
  - test -n "$TRAVIS_TAG" && make build && make push 
