---
apiVersion: v1
kind: Service
metadata:
  name: sentry
  namespace: sentry
  labels:
    name: sentry
spec:
  ports:
  - name: webhook
    port: 443
  selector:
    name: sentry 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sentry
  namespace: sentry
  labels:
    name: sentry
spec:
  replicas: 1
  template:
    metadata:
      name: sentry 
      labels:
        name: sentry
    spec:
      containers:
        - name: webhook
          image: jasonrichardsmith/sentry:0.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: sentry
        - name: config
          configMap:
            name: sentry-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentry-config
  labels:
    name: sentry-config
  namespace: sentry
data:
  config: |-
    ---
    sentryConfig:
      limits:
        enabled: true
        cpu:
          min: 1
          max: 1
        memory:
          Min: 1
          Max: 1
        audit: true
        ignoredNamespaces:
          - "test1"
          - "test2"
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sentry
webhooks:
  - name: sentry.jasonrichardsmith.org
    clientConfig:
      service:
        name: sentry
        namespace: sentry
        path: "/"
      caBundle: "${CA_BUNDLE}"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
