---
sentryConfig:
  limits:
    enabled: true
    cpu:
      min: 1
      max: 1
    memory:
      Min: 1
      Max: 1
    audit: true
    ignoredNamespaces:
      - "test1"
      - "test2"
  requests:
    enabled: true
    cpu:
      min: 1
      max: 1
    memory:
      Min: 1
      Max: 1
    audit: true
    ignoredNamespaces:
      - "test3"
      - "test4"
