---
limits:
  enabled: true
  ignoredNamespaces:
    - "test2"
    - "test3"
  cpu:
    min: 1G
    max: 1G
  memory:
    min: 1G
    max: 1G
healthz:
  enabled: true
  ignoredNamespaces:
    - "test1"
    - "test3"
tags:
  type: Pod
  enabled: true
  ignoredNamespaces:
    - "test1"
    - "test2"
