---
apiVersion: v1
kind: Namespace
metadata:
  name: test1
  labels:
    name: test1
---
apiVersion: v1
kind: Pod
metadata:
  name:      nocpu
  namespace: test1
  labels:
    test: label
spec:
  containers:
    - name:  pause
      image: k8s.gcr.io/pause
      resources:
        limits:
          memory: 1.5G

